//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int ID { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Phonenumber { get; set; }
        public int UserRole { get; set; }
    
        public virtual tblRole tblRole { get; set; }
    }
}
